name: conclude
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - pdf2image
  - pytesseract
  - tesseract
  - ipykernel
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - langchain-community
      - ollama



