name: conclude
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - pdf2image
  - pytesseract
  - tesseract
  - flask
  - flask-cors
  - ipykernel
  - pip
  - pip:
      - langchain-community
      - ollama


